platform: linux

image_resource:
  type: custom-type-poc
  source:
    repository: busybox
    tag: latest

inputs:
- name: guest-test-infra

outputs:
- name: rendered

run:
  path: sh
  args:
  - -exc
  - echo hello-world

